// Local demo: deploys mocks + engine + splitter on a running `npx hardhat node`, warms up the oracle,
// drops the price so bonds are open, credits the mock escrow, and writes site/config.local.js.
//   npx hardhat run scripts/dev-local.js --network localhost
const { ethers, network } = require("hardhat");
const fs = require("fs");
const path = require("path");

const Q96 = 1n << 96n;
const sqrtP = (s) => BigInt(s) * Q96;
const EPOCH = 60; // 1-minute epochs for the demo
const PARAMS = { maxBonusBps: 5000, bandBps: 5000, entryBurnBps: 100, penaltyBps: 2000, releaseBps: 1000, stakingShareBps: 5000, window: 24, vestEpochs: 3, minSamples: 2 };
const mine = async (secs) => { await network.provider.send("evm_increaseTime", [secs]); await network.provider.send("evm_mine"); };

async function main() {
  const [deployer, guardian, treasury, user] = await ethers.getSigners();
  const token = await (await ethers.getContractFactory("MockERC20")).deploy();
  const sv = await (await ethers.getContractFactory("MockStateView")).deploy();
  const pm = await (await ethers.getContractFactory("MockPoolManager")).deploy(await token.getAddress(), ethers.parseEther("1000000"));
  await token.mint(await pm.getAddress(), ethers.parseEther("500000000"));
  await token.mint(user.address, ethers.parseEther("25000000"));
  await token.mint(deployer.address, ethers.parseEther("25000000"));
  const engine = await (await ethers.getContractFactory("BondEngine")).deploy(
    await token.getAddress(), await pm.getAddress(), await sv.getAddress(), ethers.ZeroAddress, 0, 200, guardian.address, EPOCH, PARAMS);
  const escrow = await (await ethers.getContractFactory("MockEscrow")).deploy();
  const splitter = await (await ethers.getContractFactory("FeeSplitter")).deploy(await escrow.getAddress(), treasury.address, 6000);
  await splitter.setProtocol(await engine.getAddress());

  await sv.set(sqrtP(1000)); // 1,000,000 tokens per ETH
  await engine.start();
  for (let i = 0; i < 5; i++) { await mine(EPOCH + 1); await engine.poke(); }
  // some ETH already flowing: 10 ETH of "creator fees" harvested once (6 to treasury, 4 to engine), 3 ETH still pending
  await escrow.credit(await splitter.getAddress(), { value: ethers.parseEther("10") });
  await splitter.harvest();
  await escrow.credit(await splitter.getAddress(), { value: ethers.parseEther("3") });
  // user stakes a bit and a price drop opens bonds at ~36% discount
  await token.connect(user).approve(await engine.getAddress(), ethers.MaxUint256);
  await engine.connect(user).stake(ethers.parseEther("2000000"));
  await sv.set(sqrtP(1250));
  await mine(EPOCH + 1); await engine.poke(); // buyback happens, stakers get ETH

  const cfg = `// generated by scripts/dev-local.js — local Hardhat node only
window.BOND_CONFIG = Object.assign(window.BOND_CONFIG || {}, {
  name: "NADIR",
  chainId: 31337,
  chainName: "Hardhat local",
  rpc: "http://127.0.0.1:8545",
  rpcs: ["http://127.0.0.1:8545"],
  multicall: null,
  explorer: "http://127.0.0.1:8545",
  engine: "${await engine.getAddress()}",
  splitter: "${await splitter.getAddress()}",
  token: "${await token.getAddress()}",
  tokenSymbol: "MOCK",
  treasuryBps: 6000,
  devPrivateKey: "0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6", // PUBLIC hardhat test key (account #3), local node only, never holds funds
});
`;
  fs.writeFileSync(path.join(__dirname, "..", "site", "config.local.js"), cfg);
  console.log("engine", await engine.getAddress(), "\nsplitter", await splitter.getAddress(), "\ntoken", await token.getAddress());
  console.log("site/config.local.js written. Serve ./site and open it.");
}
main().catch((e) => { console.error(e); process.exit(1); });
